version: "3.8"

services:
  automation-ui-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: automation-ui-backend
    ports:
      - "3034:5000"
    env_file:
      - backend/.env
    restart: always
    networks:
      - automation-network

  automation-ui-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: automation-ui-frontend
    ports:
      - "3035:5001"
    env_file:
      - frontend/.env
    restart: always
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge